### ISSUE TITLE
Null Safety error

### ISSUE THREAD

**Issue by Naveenkumarar** [razmik-gharibyan/clear_all_notifications#1]
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

- package:clear_all_notifications

For solutions, see https://dart.dev/go/unsound-null-safety

FAILURE: Build failed with an exception.

* Where:
Script '/Users/naveenkumar/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/naveenkumar/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 44s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by razmik-gharibyan** [comment]
I have migrated package to null safety.
